name: claw
version: '${project.version}'
main: com.summit.claw.claw.Claw
api-version: '1.20'
authors: [ StakeTheSteak ]
description: C.L.A.W. (Collect, Locate, Annihilate, Win)
website: https://summitmc.xyz/
commands:
  claw:
    description: Root command
    usage: /<command>