name: Claw
version: '1.0-SNAPSHOT'
main: com.summit.claw.claw.Claw
api-version: '1.20'
authors: [ StakeTheSteak ]
description: C.L.A.W. (Collect, Locate, Annihilate, Win)
website: https://summitmc.xyz/
commands:
  claw:
    description: Root command for C.L.A.W.
    Usage: /claw
    permission-message: You do not have permission to use /claw.
    permission: claw.claw
  open:
    description: Opens the menu GUI for C.L.A.W.
    Usage: /[claw] open
    permission-message: You do not have permission to use the /claw open command.
    permission: claw.claw.open
  generate:
    description: Generates a challenge for the current in game day
    Usage: /[claw] generate
    permission-message: You do not have permission to use the /claw generate command.
    permission: claw.claw.generate