name: claw
version: '1.0-SNAPSHOT'
main: com.summit.claw.claw.Claw
api-version: '1.20'
authors: [ StakeTheSteak ]
description: C.L.A.W. (Collect, Locate, Annihilate, Win)
website: https://summitmc.xyz/
